{% extends _layout %}

{% block content %}

An uncaught Exception was encountered

Type:        {{get_class(exception)}}
Message:     {{message}}
Filename:    {{exception.getFile()}}
Line Number: {{exception.getLine()}}

{% if defined('SHOW_DEBUG_BACKTRACE') and SHOW_DEBUG_BACKTRACE === TRUE %}

Backtrace:
	{% for error in exception.getTrace() %}
		{% if isset(error['file']) and strpos(error['file'], realpath(BASEPATH)) !== 0 %}
	File: {{error['file']}}
	Line: {{error['line']}}
	Function: {{error['function']}}
		{% endif %}
	{% endfor %}
{% endif %}
{% endblock %}
